# My Variables
@contentType = application/json
# @baseurl = https://backend-v2.onrender.com/api
@baseurl = http://localhost:4000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzdmMjBhZGI0ODEwN2YyZDk2Mjc0MDYiLCJpYXQiOjE2Njk5NTg5MjYsImV4cCI6MTY3MDIxODEyNn0.KkEAl_JpoIU2h7uMATT2Ec67QLRyTeLOPV7jRAr7q_8


### login
POST  {{baseurl}}/user/login
Content-Type: {{contentType}}

{
    "email": "mirja@mirja.fi",
    "password": "45RFgh##@$"
}


### POST Request
POST {{baseurl}}/workouts/
Content-Type: {{contentType}}
Authorization: bearer {{token}}

{
    "title":"Situps 2022-12-02",
    "reps":60,
    "load":1
}

### POST Request
POST {{baseurl}}/workouts/
Content-Type: {{contentType}}
Authorization: bearer {{token}}

{
    "title":"Workout 2022-11-30",
    "reps":40,
    "load":10
}

### GET Request
GET {{baseurl}}/workouts
Content-Type: {{contentType}}
Authorization: bearer {{token}}

### GET Request
GET {{baseurl}}/workouts/6386e10ad8e5f9250c33591a
Content-Type: {{contentType}}
Authorization: bearer {{token}}

### GET Request (Authorization error)
GET {{baseurl}}/workouts/6379e1849df16cc3df69bcb2
Content-Type: {{contentType}}

### GET Request (does not exist)
GET {{baseurl}}/workouts/625158890e75b4ff2a109ab9999
Content-Type: {{contentType}}
Authorization: bearer {{token}}


### DELET Request   (Authorization error)
DELETE {{baseurl}}/workouts/625158890e75b4ff2a109ab9999
Content-Type: {{contentType}}

### DELET Request
DELETE {{baseurl}}/workouts/6386e10ad8e5f9250c33591a
Content-Type: {{contentType}}
Authorization: bearer {{token}}

### DELET Request  (does not exist)
DELETE {{baseurl}}/workouts/6251a0ed1317e5dff269f8aa
Content-Type: {{contentType}}
Authorization: bearer {{token}}

### unknown end point
GET {{baseurl}}/workoutsss/15
Content-Type: {{contentType}}

### PUT  Request
PATCH {{baseurl}}/workouts/6379e2969df16cc3df69bccc
Content-Type: {{contentType}}
Authorization: bearer {{token}}

{
    "reps":579,
    "load":544
}


### Signup
POST  {{baseurl}}/user/signup
Content-Type: {{contentType}}

{
    "email": "matti55@matti.fi",
    "password": "R3g5T7#gh"
}

### login
POST  {{baseurl}}/user/login
Content-Type: {{contentType}}

{
    "email": "matti55@matti.fi",
    "password": "R3g5T7#gh"
}
